declare const consolationMenu: any;
declare const exec: any;
declare const fs: any;
declare const path: any;
declare const program: any;
declare const yaml: any;
declare const R: any;
declare function runCommand(res: any): void;
declare function show(menu: any): Promise<void>;
declare function removeEmptyLines(input: any): any;
declare function getConfig(opts: any): Promise<any[]>;
declare function run(program: any): Promise<string>;
